### ISSUE TITLE
Activating the plugin gives an error

### ISSUE THREAD

**Issue by Igor-Iugin** [nr-4/PowerToys-Run-Plugin-RiderWorkspaces#1]
![изображение](https://user-images.githubusercontent.com/56183592/182325016-c8fb979f-71c1-4432-9f78-d708cdb03952.png)

**Comment by ieviev** [comment]
if you go to %APPDATA%\JetBrains\, is there a Rider2022 folder there?
![image](https://user-images.githubusercontent.com/36763595/182364139-3cdb2a5e-f1a8-473c-9e49-75313817f72a.png)

**Comment by Igor-Iugin** [comment]
I'm sorry, I misunderstood the essence of the application. I wanted to use it with WebStorm.
Can you tell me how you can reconfigure the path to the folder?

**Comment by ieviev** [comment]
@Igor-Iugin i havent tried this with WebStorm yet, but i'll see if i can get it working with webstorm - i'll let you know

**Comment by ieviev** [comment]
@Igor-Iugin got it working with WebStorm, see if this works for you

https://github.com/aciq/PowerToys-WebStormWorkspaces/releases/tag/v0.61.0

EDIT: wait i forgot the webstorm exe

**Comment by ieviev** [comment]
@Igor-Iugin okay now it works
https://github.com/aciq/PowerToys-WebStormWorkspaces/releases/tag/v0.61.1

**Comment by Igor-Iugin** [comment]
1. For some reason I can't access other projects. Gives only 1
2. It gives an error when opening the project. log: [2022-08-02.txt](https://github.com/aciq/PowerToys-Run-Plugin-RiderWorkspaces/files/9242918/2022-08-02.txt)

**Comment by ieviev** [comment]
seems that it cant find webstorm.cmd on PATH,

if you install it from Jetbrains Toolbox it'll add it automatically, but maybe you can create it yourself

![image](https://user-images.githubusercontent.com/36763595/182395928-437fae96-f736-481c-af1c-37f9a74ce779.png)

the file's contents look like this
```
@echo off
rem Generated by JetBrains Toolbox 1.25.12424 at 2022-08-02T14:38:48.575515500

set waitarg=
set ideargs=

:next
set "passwait="
if "%~1"=="--wait" set passwait=1
if "%~1"=="-w" set passwait=1
if defined passwait (set waitarg=/wait)
if not "%~1"=="" (
  if defined passwait (set "ideargs=%ideargs%--wait ") else (set "ideargs=%ideargs%%1 ")
  shift
  goto next
)

start "" %waitarg% C:\Users\kast\AppData\Local\JetBrains\Toolbox\apps\WebStorm\ch-0\222.3345.108\bin\webstorm64.exe %ideargs%
```

**Comment by Igor-Iugin** [comment]
You're right. With JetBrains Toolbox your plugin works.
I think this should be added to the requirements in the README
